.github/workflows/test_and_deploy.yml
The tests currently take a somewhat long time to run on CI. It's partly due to the test data being downloaded from GIN every time the tests start. This is not an issue for local tests because `pooch` caches the data locally.
This PR adds caching of the test data during GitHub actions, which allows its reuse across the test matrix (avoiding repeated downloads). I expect this to speed up CI.
The action is copied from brainglobe: https://github.com/brainglobe/brainglobe-napari/blob/8598161e49f995ebd0e765de3ef4c65f001dfe8f/.github/workflows/test_and_deploy.yml#L57-L63
=> Cache test data in gh actions workflow

.github/workflows/test_and_deploy.yml, movement/datasets.py, movement/io/validators.py, pyproject.toml
[Python 3.9](https://docs.python.org/3/whatsnew/3.9.html) introduced type hinting generics in standard collections via [PEP 585](https://peps.python.org/pep-0585/).
Replaced typing.list to list for datasets.py and validators.py. 
Also changed typing.collections to collections.abc.Iterable for validators.py. 
Did not remove typing.Optional, typing.Union, typing.Any, typing.Literal and typing.ClassVar as these were not mentioned to be deprecated on https://peps.python.org/pep-0585/. 
Removed support for Python 3.8 from the following files:
- pyproject.toml
- .github/workflows/test_and_deploy.yml
=> Deprecate support for python 3.8

CONTRIBUTING.md, README.md, docs/source/conf.py, docs/source/getting_started.md
@adamltyson I think it's time to switch the docs website from the default gh-pages URL to movement.neuroinformatics.dev
Any easy way to have the [old link](https://neuroinformatics-unit.github.io/movement/) redirect to the new one (if it's complicated, nevermind)?
=> Changed documentation website URL

pyproject.toml
This affects the URLs appearing on PyPI.
I changed the documentation URL to https://movement.neuroinformatics.dev and the user support URL to the appropriate [zulip stream](https://neuroinformatics.zulipchat.com/#narrow/stream/406001-Movement).
I also fixed the formatting of the names of those URLs, e.g. "Bug Tracker" instead of "bug_tracker", which should improve their readability on PyPI.
=> Updated project URLs in pyproject.toml

movement/logging.py
There are 3 possible cases in ``logging.configure_logging()``:
- logger with the given name is not configured
- logger with the given name is configured but path has not changed
- logger  with the given name is configured and path has changed
We only want to (re)configure logging in the first and third cases.
This PR removes the need for [ ``else: return``](https://github.com/neuroinformatics-unit/movement/blob/7dec1532a415b8d9b3885a5c862cfc3b86823e0f/movement/logging.py#L45-L47) for the second case, while taking into account all three cases. It also avoids[ mutating ``handlers`` while iterating through it](https://github.com/neuroinformatics-unit/movement/blob/7dec1532a415b8d9b3885a5c862cfc3b86823e0f/movement/logging.py#L43-L44), by calling …
=> Refactor configure_logging

docs/source/conf.py, movement/io/load_poses.py, tests/conftest.py, tests/test_integration/test_io.py, tests/test_unit/test_load_poses.py, tests/test_unit/test_save_poses.py
This PR enables `load_poses._load_from_sleap_labels_file` to load pose tracks from a SLEAP .slp file consisting of either:
- user-labelled instances only,
- predicted instances only, or
- a mix of user-labelled and predicted instances
This PR adds:
- `load_poses._sleap_labels_to_numpy`, a function that converts SLEAP `Labels` to a NumPy array, adapted from [`Labels.numpy()`](https://github.com/talmolab/sleap-io/blob/9a04f7feac0397d7d7bed9fb79f205678cccf9f8/sleap_io/model/labels.py#L92-L178) from the [`sleap_io`](https://github.com/talmolab/sleap-io) package, but prioritises user-labelled instances over predicted instances when the .slp file consists of a mix of user-labelled and predicted instances. This behaviour …
=> SLEAP read user labels

movement/io/save_poses.py, tests/conftest.py, tests/test_integration/test_io.py, tests/test_unit/test_save_poses.py
This PR adds the functionality to save xarrays as a dictionary of individual pandas dataframes for to_dlc_df and as multiple files for each individual for to_dlc_file. This is based on the split_individuals: bool parameter, if True it will split the data for each individual, if false it will save it as a multi-animal file. 
This PR addresses Issue #39. 
The PR was tested on a Juypter Notebook against the four scenarios, (credit to @niksirbi):
* The xarray.Dataset has multiple (>1) individuals and the user wants to save it to a multi-animal DeepLabCut dataframe. This currently works with the existing functions.
* The xarray.Dataset has only 1 individual but the user still wants to save it to a multi-animal DeepLabCut dataframe, including the …
=> Ability to save multi-animal pose tracks to single-animal files

movement/datasets.py
I've updated the [test datasets on GIN](https://gin.g-node.org/neuroinformatics/movement-test-data), specifically:
- I've added two sample output .csv files from LightningPoses (prefixed with 'LP')
- I've reduced the 'DLC_two-mice.predictions.csv` file in size, specifically I've extracted the first 10 minutes from it (previously this file was > 110 MB)
The `poses_files_metadata.yaml` and `poses_registry.txt` files have been updated accordingly and now contain the updated sha256 hashes.
This PR adds the new files and hashes to the dataset registry in `datasets.py`.
This is a pre-requisite for un-blocking #74. After this one gets merged, you can get started on that issue @DhruvSkyy
@b-peri tagging you as a reviewer so you're aware of these changes. After we merge this, you'll probably have …
=> Added LightningPose data to pooch dataset registry

movement/io/load_poses.py, tests/test_unit/test_load_poses.py
This PR enables SLEAP files (.h5 and .slp) without Tracks to be loaded.
This PR resolves #89 
Relevant tests have been added and run
=> Add support for loading "trackless" SLEAP files

CONTRIBUTING.md, docs/source/api_index.rst, docs/source/conf.py, docs/source/getting_started.md, movement/io/load_poses.py, movement/io/save_poses.py, tests/conftest.py, tests/test_integration/test_io.py, tests/test_unit/test_load_poses.py, tests/test_unit/test_save_poses.py
This PR enables _movement_ datasets to be exported as SLEAP-style .h5 files.
1. Adds:
- `to_sleap_analysis_file` which converts an xarray pose tracks dataset (cleaned using `_remove_unoccupied_tracks`) to a SLEAP-style .h5 analysis file, and the relevant documentation to the API docs
- documentation  to "saving data" in "Getting started" 
- file path and dataset validation functions in `save_poses.py`
- relevant tests for the new functions, and rewrites reused test parameters as fixtures
2. Replaces the [broken pooch URL](https://www.fatiando.org/pooch/latest/index.html) with their [GitHub repository URL](https://github.com/fatiando/pooch) to pass linkcheck when building docs.
3. Refactors file and file path …
=> Export SLEAP .h5 analysis files

README.md
The admonitions (Note and Warning) on the GitHub README were not rendering properly, because I had used an unsupported syntax. I've fixed them so that they render correctly.
=> Fix admonition rendering in README

CONTRIBUTING.md, docs/source/getting_started.md, pyproject.toml
Currently, we have a two-step installation process:
1. Create a conda environment, with `pytables` installed:
```sh
conda create -n movement-env -c conda-forge python=3.10 pytables
conda activate movement-env
```
2. Install movement itself.
```sh
pip install movement
```
We would like to simplify it to a single step, so users can simply `pip install movement`. That can be preceded by `conda create -n movement-env python=3.10`, if they want to install it in a fresh environment (which we still recommend).
As per @willGraham01's suggestion, we now require `pandas[hdf5]` instead of vanilla pandas. See #91 for more details on this.
Closes #91 
Tested locally on an M2 Mac and on CI across platforms.
No.
The installation …
=> Remove pytables as a conda dependency

.github/workflows/test_and_deploy.yml, docs/source/api_index.rst, docs/source/getting_started.md, movement/io/load_poses.py, movement/sample_data.py, tests/test_unit/test_load_poses.py
Creates a generic function from_file() which is identical to: 
- from_dlc_file()
- from_sleap_file()
- from_lp_file()
Can be called by specifying source software, 
```python
def from_file(
file_path: Union[Path, str],
source_software: Literal["DeepLabCut", "SLEAP", "LightningPose"],
fps: Optional[float] = None
``` 
Closes #98
=> Provide a generic load_poses.from_file() function #107

.github/workflows/test_and_deploy.yml, CONTRIBUTING.md, docs/source/getting_started.md, pyproject.toml
- Many of our users will use M1/2 Macs
- We want to double-check if simple pip install works on M1/2 Macs (or if we have to revert to conda, see #104)
closes  #123 
The real test are the CI checks in this PR.
No
No
The CI tests were failing on M1 runners, because the hdf5 binaries could not be found (see discussion below). Therefore, this PR has been amended to also change `movement`'s installation procedure, which should now be:
```bash
conda create -n movement-env -c conda-forge python=3.10 hdf5
conda activate movement-env
pip install movement
```
The above should work cross-platform.
I've renamed the PR from "Include CI tests on macOS 14 M1 runner" to "Include M1 runners in CI and update install instructions accordingly".
=> Include M1 runners in CI and update install instructions accordingly

.github/workflows/test_and_deploy.yml
This will have to wait until @lochhh has tested the updated action in [PR 128](https://github.com/neuroinformatics-unit/movement/pull/128), and a new v2 release of NIU actions is made.
=> Add codecov token to test_and_deploy.yml

CONTRIBUTING.md, docs/source/conf.py, docs/source/environment.yml
Would be nice for people to be able to interactively run our sphinx-gallery examples in the browser, without the need for installing anything.
It configures `sphinx-gallery` to integrate with binder, as described in the [relevant section of sphinx-gallery docs](https://sphinx-gallery.github.io/stable/configuration.html#binder-links).
It also adds an `environment.yml` file which specifies the dependencies needed for binder to run the examples. It was not possible to simply reuse the `pyproject.toml` or the `docs/requirements.txt` file for this purpose.  This is probably not a bad thing, since the examples may rely on additional packages that are not among our dependencies, and sphinx-related dependencies (found in …
=> Add binder configuration and dependencies

.github/workflows/docs_build_and_deploy.yml, .pre-commit-config.yaml, CONTRIBUTING.md, pyproject.toml, tests/conftest.py
We are already using `codespell` on several other repos and it works quite well for catching common misspellings.
=> Add and configure codespell

docs/source/community/roadmap.md
I discovered that sphinx can render checklists using the "normal" markdown syntax.
I thinks it's cool to show our progress on the current v0.1 milestone.
=> Show short-term milestone as checklist

movement/io/save_poses.py, tests/test_unit/test_load_poses.py
Multiple instances of the following warning are being raised during tests:
> FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`
It uses `Datasets.sizes` instead of `Dataset.dims` when getting the lengths of each dimension. `Dataset.dims` is still in use when we simply want the names of the dimensions.
Existing tests still pass.
No.
No
=> use Dataset.sizes instead of Dataset.dims for getting dimension sizes

.github/workflows/docs_build_and_deploy.yml, .github/workflows/test_and_deploy.yml, CONTRIBUTING.md
I've enabled [Merge Queues](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/) for the `main` branch.
For this to work in conjunction with our CI, `merge_group` has to be added as a workflow trigger. This [trigger will be emitted when a PR is marked as "Merge when Ready"](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions).
In our day-to-day work this simply means that PRs are accepted by clicking "Merge when Ready" and Github will automatically perform the necessary CI checks and merge PRs in first-in-first-out order.
It was not immediately apparent to me why the new "merge_group" trigger is needed. This …
=> add merge_group as workflow trigger

.pre-commit-config.yaml, CONTRIBUTING.md, README.md, docs/source/conf.py, examples/README.rst, movement/filtering.py, movement/io/load_poses.py, movement/io/save_poses.py, movement/io/validators.py, movement/logging.py, movement/sample_data.py, pyproject.toml, tests/test_unit/test_logging.py, tests/test_unit/test_save_poses.py
We use `ruff` for linting and `black` for auto-formatting. With the introduction of `ruff.format` (a drop-in replacement for `black`, but faster) there is no longer need to be using `black`. This prompted me to overhaul our entire lint/format setup.
I went through the [scientific python development guide for style and static checks](https://learn.scientific-python.org/development/guides/style/) and applied the recommendations that make sense for `movement`.
In summary these are:
- switch from `black` to `ruff.format`
- add some more [ruff rules](https://docs.astral.sh/ruff/rules/). I ended up with the following set (which includes the most popular ruff rules):
```yaml
lint.select = [
"E",   # pycodestyle errors
"F", …
```
=> Overhaul linting and formatting

docs/requirements.txt, docs/source/environment.yml, pyproject.toml
Closes #158 . Thanks @antortjim for reporting the bug.
We now depend on `xarray[accel,viz]`, instead of just `xarray[accel]`, meaning we also require `matplotlib` and `seaborn`.
Accordingly, `matplotlib` is no longer listed as an additional dependency for docs and binder (no need, since it will now come bundled with `movement`).
See #158 and [xarray's installation instructions](https://docs.xarray.dev/en/stable/getting-started-guide/installing.html#instructions).
Example notebooks were run in a fresh environment.
No.
No.
=> Add viz extras to xarray dependency

examples/compute_kinematics.py, examples/filter_and_interpolate.py, examples/load_and_explore_poses.py, movement/analysis/kinematics.py, movement/filtering.py, movement/io/load_poses.py, movement/io/save_poses.py, movement/io/validators.py, movement/logging.py, movement/move_accessor.py, movement/sample_data.py, movement/utils/vector.py, pyproject.toml, tests/conftest.py, tests/test_integration/test_io.py, tests/test_integration/test_kinematics_vector_transform.py, tests/test_unit/test_filtering.py, tests/test_unit/test_kinematics.py, tests/test_unit/test_load_poses.py, tests/test_unit/test_logging.py, tests/test_unit/test_move_accessor.py, tests/test_unit/test_sample_data.py, tests/test_unit/test_save_poses.py, tests/test_unit/test_validators.py, tests/test_unit/test_vector.py
We recently implemented a linting/code formatting overhaul, relying on `ruff` #156.
However, we are still missing linting/formatting for docstrings. Would be nice to have them all formatted in a uniform way.
It adds the ["D" (pydocstyle) ruleset](https://docs.astral.sh/ruff/rules/#pydocstyle-d) to the `ruff` config.
That enforces a bunch of rules on docstring formatting, and most problems are auto-fixed.
However, I had to fix lots of issues manually, because many of our existing docstrings were non-compliant.
The rules that necessitated most manual work were the ones stipulating that docstrings should start with a one-line short description ending in a period, optionally followed by a longer description (separated …
=> Enforce linting of docstrings

pyproject.toml
There's nothing to compiled in movement, so this can be removed.
=> Remove cibuildwheel config

.github/workflows/test_and_deploy.yml
This is because GitHub recently updated `macos-latest` to mean `macos-14` (M1) instead on `macos-12` (intel mac).
Therefore, with our current setup we are running duplicate tests on M1 Macs and none on intel Macs.
I changed the CI testing matrix to include both `macos-latest` (M1) and `macos-13` (intel).
I'm using [GitHub docs for reference](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
=> Changed macos runners for GitHub CI

pyproject.toml
I had completely forgotten this was still set to "Pre-Alpha".
I think "Alpha" is justified in our case?
=> update pypi dev status from pre-alpha to alpha

examples/compute_kinematics.py, movement/move_accessor.py, tests/conftest.py, tests/test_integration/test_kinematics_vector_transform.py, tests/test_unit/test_move_accessor.py
This PR closes #162.
This PR refactors the `MoveAccessor` by replacing the kinematic property accessors with "convenience" `compute` methods, which allow users to compute kinematic variables of a Dataset, for instance, by calling `ds.move.compute_velocity()`. It does so by overriding the `__getattr__` method to "forward" method calls to the relevant modules. Atm, it only calls `compute_` methods implemented in the `kinematics` module, but this can be expanded upon for other modules as needed. 
#162
Tests have been updated accordingly.
The compute kinematics example has been updated accordingly.
=> Refactor accessor to provide methods instead of properties

movement/filtering.py, tests/conftest.py, tests/test_integration/test_filtering.py, tests/test_unit/test_filtering.py
_Edited 08/05/2024_:
This PR introduces two new smoothing functions to the `filtering` module:
1. `median_filter(ds, window_length)`: Smooths pose tracks in the input dataset by applying a median filter along the time dimension. Window length must be specified by the user, and is interpreted as being in the input dataset's time unit (usually seconds). The filter window is centered over the filter origin.
2. `savgol_filter(ds, window_length, polyorder, **kwargs)`: Smooths pose tracks over time using a Savitzky-Golay filter. Again, window length must be specified by the user, and is interpreted as being in the input dataset's time unit. The order of the polynomial used to fit the samples can optionally be specified by the user. If omitted, a default value of `2` is used. Additional keyword …
=> Implement Median and Savitzky-Golay Filters

docs/requirements.txt
For some reason, which I have since forgotten, we had pinned the sphinx version to <7.2
It could have been [this reason](https://github.com/neuroinformatics-unit/HowTo/pull/55#issuecomment-2118312367) described by @JoeZiminski. If that was the reason, it shouldn't be a problem anymore, since we are already applying the `exclude_patterns` solution.
This PR changes the dependency constraint from <7.2 to >=7.0, so we should get the latest version.
I tested with sphinx local builds, and it works without error/warnings.
Let' see if the CI passes....
=> Unpin sphinx version in docs requirements

README.md
Installation link was returning 404
Fixes installation link and adds quick install instructions. 
\
\
\
\
=> Fix installation link and add quick install

movement/io/load_poses.py
We have two private data loading functions to read DLC files into a dataframe: `_parse_dlc_csv_to_df` and `_load_df_from_dlc_h5`. 
This PR proposes to rename one of them (`_parse_dlc_csv_to_df` -> `_load_df_from_dlc_csv`) , for a more consistent naming of the two.
Renames a private data loading function.
\
No.
No because it is a private function.
- [ n/a ] The documentation has been updated to reflect any changes
=> Suggestion to rename private loader

README.md, docs/source/community/index.md, docs/source/community/mission-scope.md, docs/source/community/roadmaps.md, docs/source/index.md
For future-proofing, we decided to have in our docs a link to all our roadmaps (similar to [brainglobe](https://brainglobe.info/community/roadmaps/index.html)).
- Renames the title of the Roadmaps site to be in plural.
- Renames the .md file itself and the associated target variable for consistency.
\
Tests pass locally and in CI, docs build locally.
\
\
- [ n/a ] The documentation has been updated to reflect any changes
=> Rename roadmap -> roadmaps in docs

docs/source/api_index.rst, movement/io/load_poses.py, movement/io/validators.py, tests/test_unit/test_validators.py
The class defines a specific Deeplabcut csv format, rather than a common format in pose estimation more generally. This is clarified in the docstring but maybe it would be nice to make it more explicit with the class name.
Renames the validator class ValidPosesCSV to ValidDeepLabCutCSV.
Not sure about the high/lower case dance though, so happy to hear thoughts 👀 
None.
No.
No.
=> Suggestion to rename ValidPosesCSV to ValidDeepLabCutCSV

docs/source/conf.py, examples/compute_kinematics.py, examples/filter_and_interpolate.py, examples/smooth.py, pyproject.toml
PR #163 added median and Savitzky-Golay filters but their usages has not beed documented in tutorials/examples.
This PR adds a new "Smooth pose tracks" example that guides the users through smoothing data using either or both new filters.
Additionally, the titles and subtitles of all examples are using the imperative case (e.g. "smooth" instead of "smoothing") to be consistent with our docstrings.
Closes #179 
PRs #163 and #189 
The documentation was [built locally](https://movement.neuroinformatics.dev/community/contributing.html#building-the-documentation-locally) and inspected. This is also the recommended way of reviewing this PR, as the rendered html is more readable than the `sphinx-gallery` source file.
No.
It …
=> Added example using `median_filter()` and `savgol_filter()`

docs/source/api_index.rst, movement/io/load_poses.py, movement/io/save_poses.py, movement/io/validators.py, tests/test_integration/test_io.py, tests/test_unit/test_load_poses.py, tests/test_unit/test_save_poses.py
The public functions in the `load_poses.py` module currently assume that users are always loading data from a file (or from a DeepLabCut-style pandas dataframe). However, there are some use-cases where the data are already in Python, in the form of numpy arrays, perhaps imported with custom loaders (this is not hypothetical, a potential user has already asked for it). There is a way to convert such data into a properly-formatted `movement` dataset, but this way is not easy to find and is not documented.
Adds a `from_numpy()` function that explicitly accepts `position` (+ optional `confidence`) data in the form of numpy arrays and returns a `movement` dataset. Under the hood it calls the `ValidPosesDataset` validator …
=> Refactored modules related to input-output

.github/workflows/test_and_deploy.yml, README.md, docs/source/getting_started/installation.md, examples/compute_kinematics.py, examples/smooth.py, movement/filtering.py, movement/io/load_poses.py, movement/io/save_poses.py, movement/io/validators.py, pyproject.toml
Following [Scientific Python's SPEC-0](https://scientific-python.org/specs/spec-0000/), we are dropping support for `python v3.9` and adding support for `python v3.12`. 
In the installation instructions, the recommended python version for the conda environment was bumped from `3.10` to `3.11`, and consequently `3.11` is also the version we test across all OSes in CI.
One of the `ruff` linters (`pyupgrade`) automatically replaced all `Union` occurrences with the `|` syntax, because that was introduced in `3.10`.
I also added a badge to the README, which will automatically fetch supported Python version from PyPI and display them.
=> Update supported Python versions

movement/analysis/kinematics.py, movement/move_accessor.py, tests/test_integration/test_kinematics_vector_transform.py, tests/test_unit/test_kinematics.py, tests/test_unit/test_move_accessor.py
This PR closes #203 
This PR removes the `self.validate()` step in `move_accessor` that validates the entire dataset, and validates only the required ``position`` data variable and leaves the ``time`` validation up to the `compute_` function evoked.
This PR also uses `log_error` that logs and raises an Error, in preference to `logger.error` + `raise` calls.
Incorrect error types raised are also corrected in this PR (ValueError &rarr; AttributeError). 
#203 
Affected tests have been updated accordingly and rerun.
=> Accessor `compute_` to only validate required `position` data variable

README.md
Since [PR208](https://github.com/neuroinformatics-unit/movement/pull/208), python v3.11 is the main version we test across OSes and it's the one we recommend in the installation guide. But I'd forgotten to update the python version in the quick install section of the README. This PR rectifies that.
=> Update python version in README.md

pyproject.toml
Numpy 2.0 was released yesterday, containing some breaking API changes (syntax deprecations).
The Numpy devs have written a [migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html), and have even provided a ruff linting rule - [NPY201](https://docs.astral.sh/ruff/rules/numpy2-deprecation/)  - that "Checks for uses of NumPy functions and constants that were removed from the main namespace in NumPy 2.0".
It add NPY201 to the ruff lint config. 
I also run `pre-commit run -a` and thankfully nothing came up. Nevertheless I'll leave this rule in, so that no deprecated syntax creeps in.
n/a
Existing tests pass locally and in CI.
No.
No.
- [/] Tests have been added to cover all new functionality
- [/] The …
=> Added ruff rule to check for numpy2.0 compatibility

CITATION.CFF, MANIFEST.in, README.md, docs/source/index.md, pyproject.toml
This PR:
- Adds a citation CFF file
- Adds a citation section to the readme
- Adds a DOI badge
- Adds citation sentence to website
I've tried to make this as simple as maintain as possible. The DOI is the "general" one that represents all versions, and will resolve to the latest one. I've also kept version numbers out of it.
In terms of authors, I just used everyone who had contributed to the software, in the order suggested by Zenodo. The final publication may be different to this, but it seemed a good place to start. I suggest we don't try to hyper-optimise this, and just include everyone. The only maintenance needed will be to add new authors to this list as and when needed. Unfortunately this is in three places, but not sure if that's an issue?
I plonked the citation info on the index …
=> Add citation information

movement/validators/datasets.py, tests/test_unit/test_sample_data.py, tests/test_unit/test_validators/test_datasets_validators.py
Two small edits are needed in `ValidBboxesDataset` to continue with the bboxes work:
1. Adding `frame_array` to `ValidBboxesDataset`.
Usually running inference on a video using a detection model will output a file (often a csv) that links each detection (aka bounding box) to a frame in the video. As a result, specific frame numbers appear in the output file (see [here](https://motchallenge.net/instructions/) for a few examples). We would like to be able to pass these specific frame numbers to the bounding boxes dataset if they are defined.
2. Setting default track IDs to 1-based integers.
This follows from the discussion at #217. 
1. Adds `frame_array` as an optional attribute to the `ValidBboxesDataset`.
- If no …
=> Small edits to ValidBboxesDataset (1/4)

CONTRIBUTING.md, docs/source/conf.py, docs/source/getting_started/index.md, docs/source/getting_started/input_output.md, docs/source/getting_started/movement_dataset.md, docs/source/getting_started/sample_data.md, movement/io/load_poses.py, movement/validators/files.py
To update the Getting started docs re the new bounding box data loading functionalities.
- Edits the text in the Getting started sections to reference to the bounding boxes functionalities
- Adds the `from_numpy` methods to the input/output guide (closes #244)
- Small edits to make all sections more consistent. 
- Edits docstrings for pose loaders so that they explicitly refer to poses datasets in the API reference
Fixes #244
Follows up from feedback received in PR #229 
Docs build locally and in CI.
No.
It is an update itself.
=> Getting started docs update for bboxes

movement/validators/datasets.py, movement/validators/files.py
Closes #252 
- Adds the missing blank lines after block quote
- Adds missing double backticks 
- Hides `ValidVIATracksCSV` attrs validator functions in the API docs
- Describes validation checks at validator class-level
- Shortens validator function names `_csv_file_contains...` &rarr; `_file_contains...`
- Change `ID` in function and variable names to lowercase ([consistency issues](https://sonarcloud.io/project/issues?id=neuroinformatics-unit_movement&pullRequest=219&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true))
#252 
Docs built locally and via CI
1. do the same for `ValidVIATracksCSV`, or
2. unhide all attrs validator functions?
If we go for 1., i.e. showing only the class definition, maybe we should mention …
=> Refactor names and fix docs formatting in `validators`

pyproject.toml
Tests are failing because with Python 3.12, a `numpy` install >=2.0.0 will conflict with the latest `pandas`.
See [here](https://github.com/numpy/numpy/issues/26710) for more details.
Pins `pandas` to < 2.2.2 if the Python version > 3.12 as a temporary fix.
This results in an environment with `pandas=2.2.1` and `numpy=1.26.4` .
**Questions**
- Is it clearer to pin numpy?
- Is there a better temporary fix?
- Why did this start to cause issues today?
The issue in [numpy](https://github.com/numpy/numpy/issues/26710) - although it seems that the problem should have been fixed in [pandas 2.2.2](https://pandas.pydata.org/docs/whatsnew/v2.2.2.html#pandas-2-2-2-is-now-compatible-with-numpy-2-0) …
=> Pin pandas version for Py3.12 tests

pyproject.toml
On CI, the tests are run on all platforms, using all Python environments.
This is because the `tox-gh-actions` plugin is not mapping correctly tox environments to Python versions specified in the CI jobs.
After checking the docs of `tox-gh-actions`, it seems the issue was the addition of the `tox-requires` section.
If we use this section, we need to add the `tox-gh-actions` plugin to that section too - see https://github.com/ymyzk/tox-gh-actions#tox-requires.
Note that the jobs running tests on Python 3.12 will fail unless the fix in PR #259 is implemented.
Fixes #260.
If the fix in PR #259 is implemented, tests pass in CI and are not repeated per platform.
No.
No.
- [ n/a ] Tests have been added to cover all new …
=> Fix `tox requires` section

movement/io/load_bboxes.py, movement/io/load_poses.py, movement/move_accessor.py, tests/conftest.py, tests/test_integration/test_kinematics_vector_transform.py, tests/test_unit/test_kinematics.py, tests/test_unit/test_load_bboxes.py, tests/test_unit/test_load_poses.py, tests/test_unit/test_move_accessor.py, tests/test_unit/test_save_poses.py
This PR extends the `move.validate()` method to bounding boxes dataset.
- Extends the `validate` method of the `move` accessor to consider a bounding boxes dataset.
- Extends the current tests of the `move` accessor to cover the cases with bounding boxes dataset. To do so:
- It adds fixtures for valid/invalid bounding boxes datasets.
- It splits the `invalid_poses_dataset` fixture into separate fixtures. This allows us to reusue fixtures that are valid for both types of datasets (e.g., `empty_dataset`).
- It parametrizes current tests, to extend them to valid and invalid bounding boxes datasets
- It adds a test for the `move.validate()` method.
- Adapts other tests to the new fixtures for invalid datasets.
I am not …
=> Adapt move accessor to bboxes datasets

CONTRIBUTING.md, README.md, docs/source/community/roadmaps.md, docs/source/environment.yml, docs/source/getting_started/installation.md
This PR closes #254 and #262
This PR:
- updates the documentation to include conda installation instructions
- replaces pip install instructions in repo README quick install with conda instructions
- updates any mention of python 3.10 in the setup to python 3.11
#254 #262
Installed movement from conda locally and ran `movement info`
Docs built locally and on CI
=> Update setup docs

pyproject.toml
Reverts neuroinformatics-unit/movement#259 since pytables made [a new release](https://github.com/PyTables/PyTables/releases/tag/v3.10.0) that should be compatible with numpy > 2.0
Fixes #263
=> Revert "Pin pandas version for Py3.12 tests"

examples/compute_kinematics.py, movement/utils/vector.py, tests/test_unit/test_vector.py
We often need to compute the magnitude (norm, length) of a vector, and would be nice to have a convenient xarray-native way of doing so. Currently we can only do that by either:
- use `cart2pol` to convert to poral coordinates, and take the `rho` value
- convert to numpy array and use `np.linalg.norm`
Adds two new functions in  the`utils/vector.py` module.
1. `magnitude`: this does the obvious thing. If an array in cartesian space is passed, we return the euclidean norm. If a user passes an array in polar coordinates, we just return the `rho`.
2. `normalize`: added for convenience. This function only works for arrays in cartesian coordinates, and returns the same array divided by its magnitude. For (0,0) values …
=> Add utilities for vector magnitude and normalisation

.github/workflows/test_and_deploy.yml
We are currently using the `defaults` channel in our actions, which from Aug2024 [is not free to use for our case](https://www.anaconda.com/blog/is-conda-free)
Add `nodefaults` channel to prevent from using the `defaults` channel. See [docs](https://docs.conda.io/projects/conda/en/4.6.1/user-guide/tasks/manage-environments.html#:~:text=You%20can%20exclude%20the%20default%20channels%20by%20adding%20nodefaults%20to%20the%20channels%20list.)
\
The CI in this PR shows the `default` channel is omitted.
No.
Should we include this in our docs for our users?
- [ n/a ] The code has been tested locally
=> Remove `defaults` from test_and_deploy.yml

tests/test_unit/test_filtering.py, tests/test_unit/test_kinematics.py
`pytest` caught a bunch of FutureWarnings of this type:
> FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
To reproduce, run `pytest` locally on the `main` branch.
For cases when we actually access a dimensions size, we now switch to using `ds.sizes` (which returns a `dict("dim_name": dims_size)`), instead of `ds.dims` (which will return a set of dimensions names in future).
For cases when we just need the dim names (e.g. for checking if a given dimension exists), we keep using `ds.dims`, which works now (because it returns …
=> Fix xarray FutureWarning about dims vs sizes

movement/io/load_bboxes.py, tests/test_unit/test_load_bboxes.py
When loading bboxes datasets from a VIA tracks file, we stored the coordinates of the top-left corner of each bbox in the dataset. This is inconsistent with the current description in the docs (which always refer to the centroid of the bboxes), and also somewhat inconsistent with the rest of the tools we support.
Fixes #302  
- Transforms the top-left corner coordinates from the VIA tracks file into the centroid ones, before creating the movement dataset
- Adds some tests
Opinions on the tests are particularly welcome. I aimed to reduce the circularity but not sure if there is a better way.
No.
No, but docstrings of the relevant private functions have been updated.
=> Add bbox centroid fix

movement/analysis/kinematics.py, movement/utils/vector.py, movement/validators/arrays.py, tests/test_unit/test_kinematics.py, tests/test_unit/test_validators/test_array_validators.py
See #292 and #291 
Turns a previously private function for validating the existence of dimensions and coordinates into a public function in `validators/arrays.py/validate_dims_coords`. This function is then used in both `kinematics.py` and `vector.py`.
In kinematics, it's now also used to assert cartesian coordinates for computing displacement, velocity and acceleration.
Existing test were already indirectly covering this functionality, but I decided to also add some unit tests that directly test this new validator. These tests are also much stricter in checking that the thrown exception has the right error message.
Nope.
No, API docs will be automatically updated.
- [n/a] The documentation has been updated to …
=> General validator function for checking dimensions and coordinates

CONTRIBUTING.md
- It fixes the installation instructions for the docs dependencies
- more details on the next section.
- It combines all the dependencies installations into the same section.
- Right now, the contributors first install `movement` in a development environment, and then install a few more additional dependencies to be able to build the docs locally in a later section. In this PR I put both steps in the same section.
- Some small updates to the phrasing
- e.g., `make clean html` cleans and re-builds the docs, so there is no need to run the build command again as the text suggests.
The docs `requirements.txt` file specifies the installation of the `movement` package on its first line, as `-e .`. The dot syntax refers to …
=> Fix command for installation of docs dependencies in the guide.

docs/source/getting_started/movement_dataset.md, examples/compute_kinematics.py, examples/filter_and_interpolate.py, movement/kinematics.py, tests/test_integration/test_kinematics_vector_transform.py, tests/test_unit/test_kinematics.py
Closes #320.
The "analysis" folder was unnecessary, because it only contains the `kinematics.py` module, and it made our import statements unnecessarily long and complicated.
I removed the `analysis` folder, and moved `kinematics.py` to be a "top-level" module - i.e. instead of `movement.analysis.kinematics` we have `movement.kinematics`.
I then searched and replaced `.analysis.kinematics` with `.kinematics`, throughout the repo.
Related to #327 and #328, but those will be further discussed and tackled separately.
Existing tests still pass, and docs still build successfully.
Yes.
Automatically done.
- [n/a] Tests have been added to cover all new functionality
=> Removed "analysis" level from namespace

.gitignore, CONTRIBUTING.md, README.md, docs/Makefile, docs/convert_admonitions.py, docs/make.bat, docs/source/index.md, docs/source/snippets/animovement-tip.md, docs/source/snippets/status-warning.md
Closes #305 
Adds a "tip" admonition to the README and the website homepage. Sadly I had to duplicate the text in both places, because the syntax for creating admonition boxes is different in GitHub-flavored vs myst-markdown. We could do away with the duplication if we went for simpler rendering options, but I like how the admonitions look.
Local docs build.
=> Encourage R users to check out `animovement`

movement/kinematics.py, pyproject.toml, tests/conftest.py, tests/test_unit/test_kinematics.py
It introduces two new functions in the kinematics module:
- `compute_speed`: quite straightforward to implement, it just returns the norm of velocity, using existing `movement` functions
- `compute_path_length`: in theory also straightforward, as it should just be the sum of the norms of displacement vectors, but I spent a lot of time debating how to handle missing values. See extensive [discussion on zulip](https://neuroinformatics.zulipchat.com/#narrow/stream/406001-Movement/topic/Path.20length.20with.20missing.20values).
In the end I opted for providing two alternative nan policies, and emitting a warning if too many values are missing. Expand the dropdown below for more details.
<details>
<summary> compute_path_length() function signatures …
=> Implement `compute_speed` and `compute_path_length`

docs/source/getting_started/movement_dataset.md, movement/io/load_poses.py, tests/test_unit/test_load_poses.py
Before submitting a pull request (PR), please read the [contributing guide](https://github.com/neuroinformatics-unit/.github/blob/main/CONTRIBUTING.md).
Just moving code from #197 
- [ x] Addition of a new feature
Please reference any existing issues/PRs that relate to this PR.
Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.
If this PR breaks any existing functionality, please explain how and why.
If any features have changed, or have been added. Please explain how the
documentation has been updated.
- [x ] The code has been tested locally
- [x ] Tests have been added to cover all new functionality
=> Add the option for multiple views loading - take2

movement/cli_entrypoint.py, tests/test_unit/test_cli_entrypoint.py
This was brought up by @lochhh while reviewing #253.
> We have in movement CLI movement info. We could also have movement gui as an alias to napari -w movement.
Adds a new CLI entry point, called `movement launch`, which aliases to `python -m napari -w movement` (i.e. launch napari with the movement plugin docked). I'm open to different names for this command.
- raised during the review of #253
- PR introducing the `movement info` entry point #176
I had troubles extending the existing unit test with parametrisation, so I added a separate test for the `movement launch` command. Let me know if there's a better way.
It would be nice to test if the command works as expected on Windows.
No.
Yes, but this will be part of …
=> Launch napari plugin with `movement launch`

.pre-commit-config.yaml
With Python 3.12, `pre-commit run check-manifest` returns an error of missing dependencies -- see more details in [this issue](https://github.com/neuroinformatics-unit/python-cookiecutter/pull/126).
To fix it,`wheel` needs to be specified as a dependency of `check-manifest` in the pre-commit config.
This error doesn't show up in CI because:
- in [CI](https://github.com/neuroinformatics-unit/actions/blob/main/check_manifest/action.yml), we run `check-manifest` with Python 3.10 and without the `--no-build-isolation` flag.
- the linting action runs on [python 3.10](https://github.com/neuroinformatics-unit/actions/blob/bd77478abf60d6fac828158f4e56caf806cb6865/lint/action.yml#L12)
- Right now, when we say we support Python 3.12 in practice we mean …
=> Fix for check-manifest pre-commit hook in Python 3.12

movement/io/load_bboxes.py, movement/validators/datasets.py, movement/validators/files.py, tests/test_unit/test_load_bboxes.py, tests/test_unit/test_validators/test_datasets_validators.py, tests/test_unit/test_validators/test_files_validators.py
The current implementation gives an error when loading a dataset with a single individual.
It also has some inconveniences that I realised were a bit too strict when I started using it more. Mainly:
- the requirement for the encoding of the frames number in the filename - right now we expect the number to be prefixed by `frame_`, but often the filename is simply the frame number, so I removed this.
- when loading the frames as specified in the input file, it may be that the frames are not regularly spaced. 
- Currently this would throw an error because we check the frames are separated by exactly 1. 
- I relaxed this requirement to simply require the frame numbers increase.
- If we extract them from the VIA file they are sorted before …
=> Fix and relax bboxes requirements

docs/source/conf.py, docs/source/user_guide/input_output.md, docs/source/user_guide/movement_dataset.md, movement/io/load_bboxes.py, movement/io/load_poses.py, movement/io/save_poses.py, movement/kinematics.py, movement/validators/datasets.py, tests/conftest.py, tests/test_integration/test_kinematics_vector_transform.py, tests/test_unit/test_kinematics.py, tests/test_unit/test_load_bboxes.py, tests/test_unit/test_load_poses.py, tests/test_unit/test_validators/test_datasets_validators.py
This PR closes #236. 
This PR 
- reorders the dimensions of movement `poses` and `bboxes` datasets as follows:
- `poses`: `("time", "individuals", "keypoints", "space")` &rarr; `("time", "space", "keypoints", "individuals")`
- `bboxes`:  `("time", "individuals", "space")` &rarr; `("time", "space", "individuals")`
- updates the docs (by first checking changed files, and then searching for the keyword "shape" in the entire directory) 
- removes the duplicated `assert_dataset` in `test_load_poses` and `test_load_bboxes` by introducing a new helper class `MovementDatasetAsserts` in `conftest.py` that provides a common `valid_dataset` function to assert poses and bboxes dataset validity in tests
- replaces if-else-blocks …
=> Reorder dimensions

docs/source/conf.py, docs/source/user_guide/input_output.md, movement/io/load_poses.py, movement/validators/files.py, tests/conftest.py, tests/test_integration/test_io.py, tests/test_unit/test_load_poses.py, tests/test_unit/test_validators/test_files_validators.py
Adding support to load adipose-triangulated data.
Currently, adipose-triangulated data cannot be loaded. I love the autocorrect here.
Implement simple loading function for anipose-generated data. Anipose saves a csv file with x, y, z, score (confidence) plus more info to a `csv` file. Currently, this basic info is parsed. Additional info that is stored in the file, which could be loaded in principle but would not fit any of `movement` boxes atm:
- number of cameras each key point was triangulated from. This is a useful piece of data; if there's space for arbitrary arrays in the dataset I would add it
- back projection error: another important metrics that would be useful to pack together.
- info on the coordinate transformations …
=> Loading function for Anipose data

movement/io/load_poses.py
`mypy` was complaining on CI, see [this failure](https://github.com/neuroinformatics-unit/movement/actions/runs/12359173332/job/34491303857#step:2:236).
This started happening after https://github.com/neuroinformatics-unit/actions/pull/71 was merged and a new NIU actions release was made. Basically, `mypy` now runs on Python 3.12 instead of 3.10, so it sees some additional errors (in our case, just 1 error). I was able to reproduce the error in a Python 3.12 environment locally.
It fixed the issue `mypy` was complaining about, by ensuring that `time_coords` doesn't undergo a type change.
https://github.com/neuroinformatics-unit/actions/pull/71
Locally running `pre-commit` and `pytest`.
No.
No.
- [n/a] Tests have been …
=> Fix mypy error in py3.12

.pre-commit-config.yaml, movement/kinematics.py, tests/test_unit/test_kinematics.py
See #381 
The function concerned, `compute_forward_vector`, has [been changed](https://github.com/neuroinformatics-unit/movement/blob/fc30b5a982bd39fb2750090f989d4025d35e0db4/movement/kinematics.py#L292-L300) to now explicitly construct the `upwards_vector` with appropriate labelling, and then the result has the extra spatial dimension dropped to ensure we always drop the correct axis.
The existing unit tests have been given a similar treatment.
- The invalid inputs test has not been touched - this still passes since (functionally) nothing was wrong originally
- The [input/output test](https://github.com/neuroinformatics-unit/movement/blob/fc30b5a982bd39fb2750090f989d4025d35e0db4/tests/test_unit/test_kinematics.py#L44 …
=> Fix dims and coords returned by `compute_forward_vector`

examples/filter_and_interpolate.py, examples/smooth.py, movement/filtering.py, tests/test_integration/test_filtering.py
See #379
- Adds `**kwargs` to the `interpolate_over_time()` function, so that additional keyword arguments can be passed to underlying methods.
- `fill_value="extrapolate"` is no longer hard-coded, instead the user may alter this parameter via the aforementioned `**kwargs`. Henceworth, gaps at the edges of time series will not be filled by default.
- Removes the `method` argument from `interpolate_over_time()` function signature, as this is passed verbatim to underlying functions.
- Retains the `max_gap` argument, as its meaning is slightly different from `DataArray.interpolate_na()`.
- Adjusts the function's docstring accordingly.
- Modifies some of the examples accordingly.
The aforementioned changes broke the …
=> Pass kwargs to `interpolate_over_time`

docs/source/blog/movement-v0_0_21.md, docs/source/community/mission-scope.md, docs/source/user_guide/input_output.md, docs/source/user_guide/movement_dataset.md, examples/load_and_upsample_bboxes.py, movement/io/load_bboxes.py, movement/validators/datasets.py
A small win towards next term 😉 
There was inconsistency in our docs when referring to bounding boxes trajectories.
- replaces all references to "bounding boxes' tracks" ---> "bounding boxes tracks"
- removes the apostrophe from similar expressions (bounding boxes centroids, trajectories, dataset, arrays
#357 
Tests pass locally and in CI
No.
It includes an update to the docstrings.
=> bounding boxes' tracks  --> bounding boxes tracks

movement/utils/logging.py
The docstring states the default level is `logging.INFO` but in the function signature it is `logging.DEBUG`.
Makes the docstring match the signature.
\
Tests pass on CI.
\
\
=> Tiny fix in docstrings for `configure_logging`

examples/broadcasting_your_own_methods.py
#409 
Uses the `plot_trajectory` function in our broadcasting example to reduce load and also show-off our features.
Closes #409 
Example still works locally and after being built in the docs.
=> Use `plot_trajectory` in broadcasting example

examples/compute_polar_coordinates.py
This PR improves the performance of an example script by replacing xarray's mean() and median() functions with numpy's nanmean() and nanmedian(). The xarray functions apply reductions iteratively over subbranches, making them inefficient for simple statistical calculations. Additionally, the script was redundantly computing mean and median values twice (once for the plot and again for the legend).
This change does not affect the main functionality of the toolbox but significantly improves the performance of the example script. It provides a better user experience for those trying out the examples or adapting them to their own datasets, leading to a better impression of the project.
Replaces xarray's mean() and …
=> replace xarray median and mean with numpy

movement/validators/files.py
See [PR review](https://github.com/neuroinformatics-unit/movement/pull/393#pullrequestreview-2623540244) by @willGraham01  and @sfmig's [comment](https://github.com/neuroinformatics-unit/movement/pull/393#issuecomment-2668262241) (copy pasted below):
> > > That error message indicates that you may have tried to load a file output by SLEAP, using the DeepLabCut loader (becasue "df_with_missing" is a dataset within DeepLabCut .h5 output files). Can you try again loading the same file but with source software set to SLEAP?
> > 
> > 
> > Can confirm, this was indeed the problem 😅 Data loaded OK when I switched.
> 
> Maybe we can make the error message a bit more clear? 👀 (I encountered this and was surprised because generally movement has crystal …
=> Clarify error raised by ValidHDF5

movement/utils/vector.py, tests/test_unit/test_vector.py
See #428. `xarray.DataArray` objects cannot be indexed with boolean arrays of more than 1 dimension (despite the underlying `numpy` arrays happily being able to do so?) and we are relying on being able to do so in `compute_signed_angle_2d`.
`compute_signed_angle_2d` now indexes on the `.values` attribute of the `DataArray` when mapping `-np.pi` angles to `np.pi`.
Closes #428 
We have a new test to catch this issue, which simulates the addition of "extra" dimensions (IE non space/time) to a DataArray, which is then input into `compute_signed_angle_2d`.
Additionally, the [original code that identified the issue](https://github.com/neuroinformatics-unit/movement/issues/428#issue-2868587522) now has returned values of …
=> Fix `compute_signed_angle_2d` using 2D boolean indexing

.github/workflows/docs_build_and_deploy.yml, .github/workflows/test_and_deploy.yml, .pre-commit-config.yaml, docs/source/environment.yml, docs/source/user_guide/installation.md, pyproject.toml
Updates the Python versions to adhere to [SPEC 0](https://scientific-python.org/specs/spec-0000/)
`qt-niu` is only available for SPEC 0 Python versions (3.11-3.13). This will break the conda-forge process when it's added as a dependency. Now seemed like a good idea to update the supported versions here, as (as far as I know) all the dependencies support 3.13.
In places where the version wasn't the oldest or newest, I've tried to update it in the same way, e.g. keeping the middle version.
=> Update Python versions to adhere to SPEC 0

.github/workflows/test_and_deploy.yml
Closes #448.
Some of our dependencies are no longer providing wheels for Intel MacOS on new (3.13) versions of Python. This problem is only going to get worse, as Silicon Macs completely replace Intel Macs over tine.
This PRs removes `macos-13` (Intel Mac) runners from our CI workflow, so we will no longer test on those.
=> Remove Intel Macs from CI workflow

CONTRIBUTING.md
This PR closes #407 
Clarifies build docs guide for Windows PowerShell users by adding a note to ask users to prepend `make` commands with `.\`. 
#407 
`.\make` command tested in PowerShell and CMD
=> Add `make` docs note for PowerShell users

movement/kinematics.py, movement/roi/base.py, movement/roi/line.py, movement/utils/vector.py, tests/test_unit/test_kinematics.py, tests/test_unit/test_roi/test_angles.py
See #438 - simplifies the call signature of functions that compute angles between vectors, and allows us to use precise language in our doc-strings when describing these quantities.
Also see #427.
Both of these issues were raised in #416, but were shifted to issues to reduce the PR complexity. Now that #416 is merged, we can apply these changes. Have tagged the original, hard-working reviewers from that PR here (but probably only one pair of eyes needed) :sweat_smile: 
Removes the option to toggle the "angle direction" in (high-level) functions that compute signed angles between two vectors, in some capacity. Specifically;
- `compute_forward_vector_angle` - this function has also had it's default angle unit switched …
=> Remove toggles for signed angle computations

movement/utils/broadcasting.py, tests/test_unit/test_make_broadcastable.py
Changes to address [this issue](https://github.com/neuroinformatics-unit/movement/pull/460#issuecomment-2698356220).
It looks like we were already ignoring these errors prior to the mypy update, and the update just made mypy stricter about where we had to put the ignore statement (now needed on both lines rather than once for the function call). I have examined the mypy docs and (as far as I can tell!) what we've already got should be working completely fine.
=> `mypy` ignores are now per-line, not per-signature

examples/mouse_eye_movements.py
Adds an example (using data Sepi provided), analysing pupil movement of a mouse that is rotated on a platform in two different conditions (`black` and `uniform`).
In the example `movement` is used in the following ways:
- Import `movement ` example data (`sample_data`).
- Quickly plot the trajectory of the pupil using `plot_trajectory` from `movement.plots `.
- Quantify the velocity with which the pupil centroid moves using `compute_velocity `from the `movement.kinematics` module
- Quantify the pupil diameter using `compute_pairwise_distances ` from `movement.kinematics` to calculate the Euclidean distances between two keypoints.
- Filtering pupil diameter data using `median_filter `from the `movement.filtering` …
=> Eye movement example

README.md, docs/source/user_guide/installation.md, movement/cli_entrypoint.py, pyproject.toml, tests/test_unit/test_cli_entrypoint.py, tests/test_unit/test_filtering.py
Thanks to a user report, we found out that installing the freshly released `movement v0.1` from conda-forge doesn't include the Qt bindings. As a result, when trying to launch napari you will get:
```sh
ImportError: No Qt bindings could be found.
napari requires either PyQt5 (default) or PySide2 to be installed in the environment.
With pip, you can install either with:
$ pip install -U 'napari[all]'  # default choice
$ pip install -U 'napari[pyqt5]'
$ pip install -U 'napari[pyside2]'
With conda, you need to do:
$ conda install -c conda-forge pyqt
$ conda install -c conda-forge pyside2
Our heuristics suggest you are using 'conda' to manage your packages.
```
We considered fixing this by adding pyqt or pyside2 as an explicit dependency on our …
=> Updated GUI installation instructions

movement/io/load_poses.py
The example in the from_numpy docstring contained an incorrect confidence_array shape, which could cause errors when used.
This PR fixes an incorrect array shape in the example usage of from_numpy within the docstring. The confidence_array was mistakenly defined with the shape (n_frames, n_individuals, n_keypoints), but the function expects (n_frames, n_keypoints, n_individuals).
None
Manually verified that the corrected example runs without errors.
No
No
=> Correct confidence_array shape in from_numpy example docstring

docs/source/user_guide/gui.md, movement/napari/convert.py, movement/napari/layer_styles.py, movement/napari/loader_widgets.py, movement/napari/meta_widget.py, tests/test_unit/test_napari_plugin/test_convert.py, tests/test_unit/test_napari_plugin/test_data_loader_widget.py, tests/test_unit/test_napari_plugin/test_layer_styles.py, tests/test_unit/test_napari_plugin/test_meta_widget.py, tests/test_unit/test_napari_plugin/test_poses_loader_widget.py
To support visualising bbox datasets in napari
- Extends the napari movement widget to load bboxes centroids 
- Expands tests to bboxes cases
- Updates the user guide
The support for bboxes shapes will be dealt with in a separate PR.
Somewhat relates to the propsal in #435 since if we make both datasets more similar we wouldn't need to duplicate efforts. I realise that is a bit longer term discussion, but happy to hear thoughts on this if any.
No.
Yes, the napari user guide has been updated.
=> Extend napari plugin to bboxes' centroids

docs/source/user_guide/input_output.md, docs/source/user_guide/movement_dataset.md, movement/io/load_bboxes.py, movement/io/load_poses.py, movement/io/save_poses.py, movement/sample_data.py, tests/fixtures/datasets.py, tests/fixtures/helpers.py, tests/test_unit/test_load_bboxes.py, tests/test_unit/test_load_poses.py, tests/test_unit/test_sample_data.py
This PR is needed to prevent errors when saving datasets to NetCDF by ensuring that optional attributes are not included if they are None.
This PR prevents serialization issues by ensuring attributes such as fps, source_file, video_path, and frame_path are only added to the dataset if specified.
#420 
Pytest: Updated tests for fps handling.
Manual Testing: Ensured NetCDF serialization works.
No.
Yes. The documentation has been updated.
=> Ensure dataset attributes are not set to None

examples/boundary_angles.py
While reading the example as published on the website. I spotted a few minor issues. I decided to fix them right away, to avoid forgetting about it.
- It removes the redundant `label=ragion.name` parameter from calls to the `.plot()` method. That method assigns that label name by default.
- Mentions of (counter)-clockwise directions towards the end of the example were flipped. The updated ones should be correct (based on the video).
#440 
Local docs build.
No.
It is in itself and update of docs.
=> Small fixes to the ROI distances and angles example

tests/test_unit/test_roi/test_plot.py
This PR is to address the warning while running pytest on the terminal. 
closes the plots after they have been made. its a quick fix to avoid the warning coming up during the testing. 
Fixed this warning. 
Please reference any existing issues/PRs that relate to this PR.
Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.
No. It doesn't change the existing code 
Not required
=> Fix Runtime Warning raised by ROI plot test

docs/source/community/roadmaps.md
After we reached `v0.1`, we hadn't really defined the next short-term goal.
Adds a new section called "Focus areas for 2025" to the roadmaps page. Unlike the previous milestone, this one is not linked to a specific version number, as we are now operating with (quasi-) semantic versioning.
I tried to strike the balance between being too vague (not useful for anyone) and too detailed (we have the issue tracker and the project board for that). The bullet points listed in this section are not specific hyper-defined tasks to do, but well, "focus areas".
@neuroinformatics-unit/behaviour do you think this is a fair representation of our priorities for this year? If not, what have I missed?
Local docs build.
No.
It is itself …
=> Add focus areas for 2025 to the roadmaps page

movement/kinematics.py, tests/test_unit/test_kinematics.py
Closes #538 #539 #540
This PR fixes `_warn_about_nan_proportion` by 
- using the appropriate `>=` comparator instead of `>` to include the upper bound when selecting the data to warn about
- replaces `len(data)` with `data.size` to determine the total number of elements in `data`
The affected tests are updated accordingly by
- removing warning filters where warnings are not expected (i.e. when using valid dataset fixtures without NaNs)
- removing warning filters and checking explicitly for warnings with matching messages where expected (i.e. when using valid dataset fixtures with NaNs)
- removing unnecessary asserts in test as these are accounted for with the check mentioned in the previous point.
The relevant …
=> Fix `_warn_about_nan_proportion` bugs

movement/napari/loader_widgets.py, tests/fixtures/napari.py, tests/test_unit/test_napari_plugin/test_data_loader_widget.py
If you load multiple files as points layers and delete one of them, the frame slider is automatically updated to reflect the dimensions of the remaining data. 
However, we currently only force the slider to match the full range of frames when a new point layer is loaded, not when one is removed. So after a delete event, if any file in the remaining data has all NaN values in the first frame (index `0`) or last frame (index `n`), napari will set the frame slider to start with `1` or end at `n-1` respectively. 
I use "frame slider" to refer to what napari documentation calls "dimension slider" for clarity, since in our widget it will represent number of frames most of the time.
This PR links the frame slider check to a …
=> Fix: update frame slider after deletion of layers

README.md
The package is quite mature by now, the warning may give the false impression that we are still at a very volatile stage.
Removes the warning from the README.
The warning on the website's homepage will be automatically removed upon next release (because it's auto-generated from the README).
Local rendering of README and docs.
No.
It is an update in docs.
=> Removed warning about package being in early development

movement/kinematics.py, movement/utils/vector.py, tests/test_integration/test_kinematics_vector_transform.py, tests/test_unit/test_kinematics.py, tests/test_unit/test_vector.py
This PR ensures that derived data variables retain their correct name attributes when computed as standalone arrays.
This PR explicitly sets the name attribute for derived data variables.
#321 
Tested through unit tests.
No
Yes, this PR requires a documentation update to inform users that derived variables now have a default name attribute set automatically.
=> Ensure derived data variables have correct name

.github/workflows/docs_build_and_deploy.yml, .github/workflows/test_and_deploy.yml
We've noticed for a long time that the Windows runner in CI takes significantly longer than other runners. I suspect it's related to the cross-OS cache not working as intended, likely due to `~` resolving to a different absolute path depending on OS, see https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cross-os-cache.
Moreover, I noticed a significant slowdown in the `build_sphinx_docs` action run times, manifest since we started using videos in some of the examples. They get downloaded each time because we hadn't previously implemented caching for that action.
- Copies @IgorTatarnikov's solution for OS-specific caches in `brainglobe-workflows`: …
=> Speed up test data caching in CI

movement/io/load_bboxes.py, tests/test_unit/test_load_bboxes.py
When loading a bboxes dataset, the intermediate dataframe that we use to extract the required array data is not always sorted by (`ID`, `frame_number`) as expected. 
The current implementation causes errors if the input file is such that after sorting the input dataframe by (`ID`, `frame_number`) the `frame_number` column (by itself) is not sorted. 
This may happen for example if the lowest ID (say ID=1) is missing in the first few frames, but the next lowest ID (ID=2)  is not.
- It changes the currently implementation to ensure the data is sorted as expected
- It extends the current test to check that:
- the dataframe is sorted by frame_number and ID
- the test passes with a file in which all IDs are present in all …
=> Fix for bboxes dataset loading

pyproject.toml
Closes https://github.com/neuroinformatics-unit/movement/issues/433
Restricts napari>=0.6.0, because the aforementioned bug is solved in that release.
https://github.com/napari/napari/issues/7668
https://github.com/napari/napari/pull/7866
We'll see if CI passed without problems. I've already played with napari=0.6.0 locally without encountering any issues.
No.
No.
=> Restrict napari version to >=0.6.0

movement/napari/loader_widgets.py, tests/test_unit/test_napari_plugin/test_data_loader_widget.py
If you launch the `movement` napari widget, close it (top left cross in the **widget** window) and reopen it, we get an error:
```python
ValueError: ref "_update_frame_slider_range" is not unique
```
Changes the way we connect the `_update_frame_slider_range` function to the layer addition/deletion event. It uses a unique (default) identifier rather than the callback name as a reference.
This fixes the issue for now, but it may be worth inspecting further. This is because every time the widget is instantiated, a new callback (with the name `_update_frame_slider_range`) is added to the list of viewer callbacks. The fact that there was an error complaining about duplicates when I used the name as reference makes me …
=> Fix duplicate reference when closing and reopening napari widget

CONTRIBUTING.md, docs/source/community/people.md
- To acknowledge data contribution by @Mahi7828
- To clarify the string to search for to manually edit the contributors list.
- Adds Mahi7828 as contributor
- Changes the string to search in order to locate the contributors section in the docs. 
I suggest the change in the string because initially I copy+pasted it as is and didn't find any matches in `/movement/docs/source/community/people.md`
\
No.
Yes, it involves one.
=> Add Mahi7828 as contributor and change str to locate section

docs/source/user_guide/input_output.md, movement/io/load_bboxes.py
Fixes #536 
It clarifies what the x,y coordinates represent in a VIA tracks file, in the relevant docstring and in the user guide
#536 
No.
It involves one.
=> Clarify x,y data in VIA-tracks

docs/source/conf.py
To further advertise out [open software week](https://neuroinformatics.dev/open-software-week/index.html), which will include some `movement` training.
Add's an announcement banner to the website. This is how it looks:
Need to rebase after we fix the Sphinx issue currently causing CI failures.
=> Add announcement banner for open software week

tests/test_unit/test_napari_plugin/test_data_loader_widget.py
In PR #476 [I removed one](https://github.com/neuroinformatics-unit/movement/pull/476/commits/a4ad46a293cc5762d177b564e61e8fdadb490bd5) FutureWarning but missed another neighbouring one. 
This PR should remove the remaining FutureWarning.
**What does this PR do?** 
Follows the FutureWarning advice to avoid using private attributes that will be unavailable in the future.
Closes #593.
It should avoid the need of filtering FutureWarnings from napari in PR #592 - I wonder if we should keep these visible as they are useful. 
- [ n/a ] The documentation has been updated to reflect any changes
=> Fix remaining napari future warning

docs/source/user_guide/input_output.md, movement/io/load_bboxes.py, movement/io/load_poses.py, tests/conftest.py, tests/fixtures/napari.py, tests/test_unit/test_load_bboxes.py
Closes #596 
Replaces remaining numpy legacy random generation with Generator ([`numpy.random.default_rng()`](https://numpy.org/doc/2.2/reference/random/generator.html#numpy.random.default_rng))
#596 
Added rng fixture and updated tests 
No, but the tests in PR #360 need to be updated once the current PR is merged.
No
=> Replace numpy legacy random generation

tests/test_unit/test_load_bboxes.py
I [changed](https://gin.g-node.org/neuroinformatics/movement-test-data/commit/9a34e6c6cb254f796a36fd9f12a9495aef38146f) the path to the frame files in the GIN repo for the single crab data, to facilitate loading the data using the VIA tool.
There were two tests that needed to be updated.
Changes the expected error message in the tests to match the current GIN repo status.
\
\
\
\
=> Change path to match GIN repo current status

docs/source/conf.py
I am not yet sure why `pre-commit run --all codespell` does not detect it :-/
=> chore: run codespell throughout fixing a typo

movement/filtering.py, tests/test_unit/test_filtering.py
`movement.filtering.median_filter` has been deprecated since v0.3.0, replaced by the more general `rolling_filter`. I think it's time to remove it completely; users have had sufficient warning.
Remove the `median_filter` and all its associated warning, tests and mentions.
#455 
Locally run tests and docs build.
Yes, the `median_filter` is no longer part of the API.
Auto-updated.
- [n/a] Tests have been added to cover all new functionality
=> Completely remove deprecated median_filter function

docs/source/user_guide/input_output.md, examples/load_and_upsample_bboxes.py
The word "easily" is used 4 times in the movement docs. In two cases what follows is relatively straightforward (2/3 LOC). In two cases (about saving bounding box tracks), the following example is ~10 LOC. It's pretty minor, but in these cases I don't want a user to see something described as "easy" that they may find intimidating.
=> Remove "easily" from some longer examples

movement/transforms.py, tests/test_unit/test_transforms.py
Supersedes #553, see that PR (and the discussions below it) for a justification.
#553 
Existing test for the `scale` function were updated to check for the contents of log entries.
No.
The docstring has been expanded.
=> Add log_to_attrs decorator to scale function

.github/workflows/docs_build_and_deploy.yml, CONTRIBUTING.md
This PR closes #622 
This PR adds `main` to the manual dispatch conditional check for deploying docs to prevent manual dispatches from other branches.
#622 
On a fork, I manually ran the workflow on
- main: deploy triggered
- other branch: deploy not triggered
Clarified conditions for the docs deploy job in the relevant section in CONTRIBUTING.md
=> Restrict deploy_sphinx_docs to `main` branch on manual workflow dispatch

pyproject.toml
- [ x] Bug fix
This is a temporary measure, because numba is currently incompatible with NumPy=2.3, see https://github.com/numba/numba/issues/10105
The fix is underway https://github.com/numba/numba/pull/10147, so hopefully we can remove this soon.
But I think we have to do this for now, because I've already gotten failures to install in some environments because of this.
Upper pins NumPy to 2.3, exactly matching what we already had to do on the conda feedstock side, see [conda-forge recipe](https://github.com/conda-forge/movement-feedstock/blob/main/recipe/meta.yaml).
- https://github.com/numba/numba/issues/10105
I've opened issues as reminders to remove the pin when we can:
- …
=> Upper pin numpy to 2.3

.github/workflows/docs_build_and_deploy.yml, docs/source/blog/arc-collaboration.md
In case the movement website is not available and needs to be redeployed, `linkcheck` will fail on these external URL references (see for example the recent [linkcheck loop](https://github.com/neuroinformatics-unit/movement/actions/runs/16449971843/job/46492310327) which prevented the docs from being redeployed). The better option here is hence to use "internal" links when cross-referencing within movement docs, since `linkcheck` will only check external links.
This PR replaces external URL references to movement docs with explicit targets to prevent unnecessary linkcheck. 
https://movement.neuroinformatics.dev/examples/index.html is [no longer checked](https://github.com/neuroinformatics-unit/movement/actions/runs/16 …
=> Replace external links to movement docs with explicit targets

movement/kinematics/__init__.py, movement/kinematics/kinetic_energy.py, tests/test_unit/test_kinematics/test_kinetic_energy.py
---
This PR introduces a new utility function, `compute_kinetic_energy`, for decomposing kinetic energy into translational and rotational components for each individual. This is based on the enhancement request raised in Issue #228 by @niksirbi. It improves the analytical capabilities of the `movement` library and sets the foundation for further physics-based behavioral analysis.
---
**•  Adds the function compute_kinetic_energy() to movement/kinematics/kinetic_energy.py**
**•  Supports optional keypoint selection and custom mass dictionaries
•  Handles both "xy" and "space" dimension naming conventions in the velocity input
•  Returns an xarray with dimensions (time, individuals, energy) and coordinates …
=> feat: compute_kinetic_energy for per-individual KE decomposition (#228)

.github/workflows/docs_build_and_deploy.yml, .gitignore, docs/source/_templates/autosummary/class.rst, docs/source/_templates/autosummary/function.rst, docs/source/conf.py, docs/source/user_guide/input_output.md, examples/advanced/broadcasting_your_own_methods.py, examples/boundary_angles.py, examples/compute_head_direction.py, examples/compute_kinematics.py, examples/filter_and_interpolate.py, examples/load_and_explore_poses.py, examples/load_and_upsample_bboxes.py, examples/mouse_eye_movements.py, examples/smooth.py, movement/plots/occupancy.py, movement/plots/trajectory.py, movement/roi/base.py, movement/roi/line.py, movement/roi/polygon.py, movement/transforms.py, movement/utils/broadcasting.py
This PR closes #569 
This PR
- configures [mini-galleries](https://sphinx-gallery.github.io/stable/configuration.html#references-to-examples) for the API docs (see [example](https://www.artifact.ci/artifact/view/neuroinformatics-unit/movement/branch/mini-galleries/docs-build/html/api/movement.kinematics.compute_velocity.html#examples-using-compute-velocity) in artifact.ci preview)
- updates, adds, and fixes references to API docs in the examples and module docstrings
#569 #648
Docs built locally and on [CI](https://www.artifact.ci/artifact/view/neuroinformatics-unit/movement/branch/mini-galleries/docs-build/html/index.html)
=> Add gallery of examples in API documentation

docs/source/community/people.md
Two contributors, Eric Denovellis and Luiz Tauffer were missing from our [people page](https://movement.neuroinformatics.dev/community/people.html).
I think this omission snuck in because they were co-authors of the [NWB PR](https://github.com/neuroinformatics-unit/movement/pull/360), which our bots may have solely credited to me.
Adds them via the [manual route for GitHub users](https://movement.neuroinformatics.dev/community/contributing.html#updating-the-contributors-list).
https://github.com/neuroinformatics-unit/movement/pull/360
NaN.
No.
It is in itself an update to docs.
=> Add missing contributors

docs/source/conf.py, examples/load_and_upsample_bboxes.py
The bounding boxes example mentions we do not have a function to export bounding boxes datasets, but after PR #580 we do.
It updates the bounding boxes example to use the `save_bboxes.to_via_tracks_file` function.
#580 
Tests pass locally and in CI
No.
It is in itself.
=> Update example to show usage of `to_via_tracks_file` from PR 580

docs/source/conf.py, docs/source/user_guide/input_output.md, movement/io/load_poses.py, movement/io/save_poses.py
With [SLEAP v1.5](https://github.com/talmolab/sleap/releases/tag/v1.5.0) docs for older versions of SLEAP have migrated to http://legacy.sleap.ai/, while newer docs are at [docs.sleap.ai](https://docs.sleap.ai/). The [sleap.ai](https://sleap.ai/) URL is now a landing site for the whole project.
Updated the existing links to SLEAP and its docs. I search the repo for `sleap.ai` and `sleap:` to find the appropriate locations.
In the `myst_url_schemes` (in Sphinx's `conf.py`) we now have two SLEAP-related entries:
```python
"sleap": "https://sleap.ai/{{path}}#{{fragment}}",
"sleap-docs": "https://docs.sleap.ai/latest/{{path}}#{{fragment}}",
```
We can keep using the first one to point to the landing page (when referring …
=> Update links to SLEAP docs

examples/compute_kinematics.py, movement/io/load_poses.py, movement/kinematics/__init__.py, movement/kinematics/kinematics.py, movement/utils/vector.py, tests/test_integration/test_kinematics_vector_transform.py, tests/test_unit/test_deprecations.py, tests/test_unit/test_kinematics/test_kinematics.py, tests/test_unit/test_vector.py
Currently, `compute_displacement` computes backward displacement vectors that are not easy to interpret.
As a solution, I propose to add two twin functions: `compute_forward_displacement` and `compute_backward_displacement`, whose results are vectors whose origin point is always the position in the associated frame.
I also updated the docstrings, the example and the tests accordingly.
Additionally, I also added an example of use of `compute_path_length` function.
#136
I have tested it by running the `compute_kinematics` example and checking whether the resulting vectors follow the direction of points.
Finally, i made sure unit and integration tests were correctly adapted and passing.
Yes, it deprecates …
=> improve resulting displacement vectors
